INSERT INTO "transaction_categories" ("id", "name", "type", "color", "createdAt")
VALUES
  ('cat_exp_alimentacao', 'Alimentação', 'EXPENSE', '#f97316', CURRENT_TIMESTAMP),
  ('cat_exp_supermercado', 'Supermercado', 'EXPENSE', '#fb923c', CURRENT_TIMESTAMP),
  ('cat_exp_padaria', 'Padaria', 'EXPENSE', '#f59e0b', CURRENT_TIMESTAMP),
  ('cat_exp_feira_hortifruti', 'Feira / Hortifruti', 'EXPENSE', '#84cc16', CURRENT_TIMESTAMP),
  ('cat_exp_moradia', 'Moradia', 'EXPENSE', '#6b7280', CURRENT_TIMESTAMP),
  ('cat_exp_aluguel_condominio', 'Aluguel / Condomínio', 'EXPENSE', '#64748b', CURRENT_TIMESTAMP),
  ('cat_exp_agua', 'Água', 'EXPENSE', '#06b6d4', CURRENT_TIMESTAMP),
  ('cat_exp_energia_eletrica', 'Energia elétrica', 'EXPENSE', '#eab308', CURRENT_TIMESTAMP),
  ('cat_exp_internet_telefone', 'Internet / Telefone', 'EXPENSE', '#0ea5e9', CURRENT_TIMESTAMP),
  ('cat_exp_gas', 'Gás', 'EXPENSE', '#facc15', CURRENT_TIMESTAMP),
  ('cat_exp_transporte', 'Transporte', 'EXPENSE', '#8b5cf6', CURRENT_TIMESTAMP),
  ('cat_exp_combustivel', 'Combustível', 'EXPENSE', '#7c3aed', CURRENT_TIMESTAMP),
  ('cat_exp_estacionamento_pedagio', 'Estacionamento / Pedágio', 'EXPENSE', '#a855f7', CURRENT_TIMESTAMP),
  ('cat_exp_saude', 'Saúde', 'EXPENSE', '#ef4444', CURRENT_TIMESTAMP),
  ('cat_exp_farmacia', 'Farmácia', 'EXPENSE', '#f43f5e', CURRENT_TIMESTAMP),
  ('cat_exp_plano_saude', 'Plano de saúde', 'EXPENSE', '#dc2626', CURRENT_TIMESTAMP),
  ('cat_exp_educacao', 'Educação', 'EXPENSE', '#3b82f6', CURRENT_TIMESTAMP),
  ('cat_exp_escola_curso', 'Escola / Curso', 'EXPENSE', '#2563eb', CURRENT_TIMESTAMP),
  ('cat_exp_material_escolar', 'Material escolar', 'EXPENSE', '#60a5fa', CURRENT_TIMESTAMP),
  ('cat_exp_lazer', 'Lazer', 'EXPENSE', '#ec4899', CURRENT_TIMESTAMP),
  ('cat_exp_viagens', 'Viagens', 'EXPENSE', '#db2777', CURRENT_TIMESTAMP),
  ('cat_exp_assinaturas', 'Assinaturas', 'EXPENSE', '#be185d', CURRENT_TIMESTAMP),
  ('cat_exp_vestuario', 'Vestuário', 'EXPENSE', '#14b8a6', CURRENT_TIMESTAMP),
  ('cat_exp_cuidados_pessoais', 'Cuidados pessoais', 'EXPENSE', '#2dd4bf', CURRENT_TIMESTAMP),
  ('cat_exp_pets', 'Pets', 'EXPENSE', '#a3e635', CURRENT_TIMESTAMP),
  ('cat_exp_impostos_taxas', 'Impostos / Taxas', 'EXPENSE', '#475569', CURRENT_TIMESTAMP),
  ('cat_exp_manutencao_casa', 'Manutenção da casa', 'EXPENSE', '#78716c', CURRENT_TIMESTAMP),
  ('cat_exp_presentes_doacoes', 'Presentes / Doações', 'EXPENSE', '#f472b6', CURRENT_TIMESTAMP),
  ('cat_exp_servicos_domesticos', 'Serviços domésticos', 'EXPENSE', '#94a3b8', CURRENT_TIMESTAMP),
  ('cat_exp_cartao_credito', 'Cartão de crédito', 'EXPENSE', '#991b1b', CURRENT_TIMESTAMP),
  ('cat_exp_emprestimos_financiamentos', 'Empréstimos / Financiamentos', 'EXPENSE', '#7f1d1d', CURRENT_TIMESTAMP),
  ('cat_exp_seguros', 'Seguros', 'EXPENSE', '#1f2937', CURRENT_TIMESTAMP),
  ('cat_exp_outros', 'Outros (Despesa)', 'EXPENSE', '#9ca3af', CURRENT_TIMESTAMP),
  ('cat_inc_salario', 'Salário', 'INCOME', '#22c55e', CURRENT_TIMESTAMP),
  ('cat_inc_decimo_terceiro_bonus', '13º / Bonificação', 'INCOME', '#16a34a', CURRENT_TIMESTAMP),
  ('cat_inc_freelance', 'Freelance', 'INCOME', '#10b981', CURRENT_TIMESTAMP),
  ('cat_inc_reembolso', 'Reembolso', 'INCOME', '#14b8a6', CURRENT_TIMESTAMP),
  ('cat_inc_rendimentos_investimentos', 'Rendimentos / Investimentos', 'INCOME', '#059669', CURRENT_TIMESTAMP),
  ('cat_inc_aluguel_recebido', 'Aluguel recebido', 'INCOME', '#15803d', CURRENT_TIMESTAMP),
  ('cat_inc_venda_itens', 'Venda de itens', 'INCOME', '#65a30d', CURRENT_TIMESTAMP),
  ('cat_inc_pensao_beneficio', 'Pensão / Benefício', 'INCOME', '#0d9488', CURRENT_TIMESTAMP),
  ('cat_inc_presente_recebido', 'Presente recebido', 'INCOME', '#34d399', CURRENT_TIMESTAMP),
  ('cat_inc_outros', 'Outros (Receita)', 'INCOME', '#10b981', CURRENT_TIMESTAMP)
ON CONFLICT ("name") DO UPDATE
SET
  "type" = EXCLUDED."type",
  "color" = EXCLUDED."color",
  "deletedAt" = NULL;
